### ISSUE TITLE
remove hard-coded network-specific variables from chart-specific `values.yaml`.

### ISSUE THREAD

**Issue by boz** [akash-network/helm-charts#13]
Chart variable values should at most be kept in chain-specific `values.yaml` files

For instance:

```sh
helm install -f env/production.yaml charts/akash-node
```

Examples that should be moved (non-exhaustive):

* https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-provider/values.yaml#L15
* https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-provider/values.yaml#L18
* https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-provider/values.yaml#L10
* https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-provider/values.yaml#L10
* https://github.com/ovrclk/helm-charts/blob/main/charts/akash-node/values.yaml#L22-L25
* https://github.com/ovrclk/helm-charts/blob/main/charts/akash-node/values.yaml#L22-L25
* https://github.com/ovrclk/helm-charts/blob/main/charts/akash-ingress/values.yaml#L5

If there is another way to make charts generic over the network and installation configuration explicit, I am open to it, but this repo should not be specifying things that change from network to network or even across time for a specific network.

**Comment by sacreman** [comment]
We wanted a 1 line Helm chart install for everything that works on mainnet that is short and simple.

So we defaulted mainnnet values and people can override for other networks.
