### ISSUE TITLE
akash-node: unnecessary config overwrite

### ISSUE THREAD

**Issue by boz** [akash-network/helm-charts#19]
These *should* be configurable via environment variables:

https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-node/templates/configmap-bootstrap.yaml#L19-L21

Also:

* the first `sed` line looks very dangerous - it is not targeted at any specific variable.
* gas prices should not be hard-coded.
* address book strict should not be hardcoded.

**Comment by sacreman** [comment]
Yes, this all needs sorting out properly. It would be good to standardise exclusively on environment variables in the pod being set by chart values (defaulted). If that's possible.
