### ISSUE TITLE
akash-node: do not hard-code moniker prefix

### ISSUE THREAD

**Issue by boz** [akash-network/helm-charts#20]
This should be entirely use-controlled: https://github.com/ovrclk/helm-charts/blob/b52f46016de4a4516c6a4711fecead0cb58d7bbf/charts/akash-node/templates/configmap-bootstrap.yaml#L15

Also, `--home $AKASH_HOME` is unnecessary.

**Comment by ghost** [comment]
`configmap-bootstrap.yaml` is history
