### ISSUE TITLE
akash-provider is slowly draining users funds when is out of gas

### ISSUE THREAD

**Issue by ghost** [akash-network/helm-charts#25]
https://www.mintscan.io/akash/account/akash1fjsgc7uy2vy23juehaja3f5wzfqu8wd6rwck7p

https://www.mintscan.io/akash/txs/0D5E387041830524381FCA5D607E6918F66C69CE8FE9A8A7B320C92317182324
![image](https://user-images.githubusercontent.com/3791945/157330965-e2f12658-7d8b-4583-bc79-d7ef798c32d2.png)

User remek is having issues with his akash provider due to issue with the gas,
I'm trying to figure it out currently here https://discord.com/channels/747885925232672829/771909807359262751/950722800086319144

But the point is that the akash-provider (or rather the script it uses) should restart `akash tx` with an exponential back-off delay (10s, 20s, 40s, 80s, ...), probably capped at 8 hours so it won't keep draining the uakts.

**Comment by sacreman** [comment]
@arno01 confirms this is fixed by gas=auto so once the fix to make that work is backported to a 0.14.1 akash release we can move the chart over to use it by default.
