### ISSUE TITLE
[generic bid price script] set better pricing for storage

### ISSUE THREAD

**Issue by ghost** [akash-network/helm-charts#75]
I think we should adjust these values to get at least cheaper than AWS:
https://github.com/ovrclk/helm-charts/blob/provider-0.173.0/charts/akash-provider/scripts/price_script_generic.sh#L50-L56

Amazon charges for EBS storage (GB-month):
- $0.015 sc1 (Cold HDD)
- $0.045 st1 (Throughput Optimized HDD)
- $0.08 gp3 (General Purpose SSD)
- $0.10 gp2 (General Purpose SSD)
- $0.125 io1, io2 (Provisioned IOPS SSD)

https://aws.amazon.com/ebs/pricing/
https://calculator.aws/#/createCalculator/EBS

I am thinking of making the following adjustments to the USD prices per GB-month,

### before

```
TARGET_HD_EPHEMERAL="0.25" # previously TARGET_HD
TARGET_HD_PERS_HDD="0.30"  # beta1
TARGET_HD_PERS_SSD="0.40"  # beta2
TARGET_HD_PERS_NVME="0.45" # beta3
```

currently it gives the following prices for **16 TiB** persistent storage:
- $4096 a month for ephemeral;
- $4915 a month for HDD (beta1) persistent;
- $6553 a month for SSD (beta2) persistent;
- $7372 a month for NVME (beta3) persistent;

> to calculate this, multiple GB by TARGET price and you get the result in USD, e.g. `16*1024*0.25 = 4096`.

### after

```
TARGET_HD_EPHEMERAL="0.08" # previously TARGET_HD
TARGET_HD_PERS_HDD="0.10"  # beta1
TARGET_HD_PERS_SSD="0.12"  # beta2
TARGET_HD_PERS_NVME="0.14" # beta3
```

so that price for **16 TiB** persistent storage in Akash will be:
- $1310 a month for ephemeral;
- $1638 a month for HDD (beta1) persistent;
- $1966 a month for SSD (beta2) persistent;
- $2293 a month for NVME (beta3) persistent;

**Comment by figurestudios** [comment]
On a large scale with no profit, a TB should not cost more than [$1.50/mo](https://blog.sia.tech/cloud-storage-for-2-tb-mo-8a34043e93bb). Add some 25-35% for tax, a markup/profit margin of 25%, and we get a price of $2.53/TB for HDDs. But it's up to the providers themselves to be competitive, so making HDD's $10/TB/mo by default is reasonable where bandwidth is not a concern. But the question is who to target. If we target people who get charged by the bandwidth they're using, it must go in the hundreds or thousands per month to ensure that they get profit. But that's an unreasonable ask, as those who doesn't pay extra for that can comfortably store it for $2.53/TB/mo. I think we should call it at $10/TB/mo for HDDs. This is `$0.0089/GiB/mo` or `$145.82/16TiB/mo`. I think this is reasonable for both persistent and general-use HDD storage.

EDIT: These prices are with 1.5x redundancy. I think that providers should be able to have a 2x redundancy or to store backups every now and then, and not have to worry about being too expensive just for being reliable. This makes it to `$3.38/TB/mo` for just the simple tax and small markup, and I suppose that `$15/TB/mo` is not overly expensive. As I said, being competitive should be up to the provider if they want to be that or not, and `$15/TB/mo`, while not the cheapest it can be, is not expensive at all. This brings the prices up to `0.0134/GiB/mo` and `219.55/16TiB/mo` respectively.

EDIT 2: I do not know much about how SSDs cost to maintain vs. HDDs, but David was giving a lot of lee-way in his $1.50/TB/mo for HDDs at a 1.5x redundancy already, so I think we can utilize this lee-way here too. Roughly, 1 TB of HDD costs $37.5 to buy new. SSDs, $100. From this, I think that a fair price for SSDs is $40/TB/mo, as shown here: `($15/TB/mo / $37.5/TB/HDD) * $100/TB/SSD = $40/TB/mo`, which gives us `$0.036/GiB/mo` & `$582.07/16TiB/mo`. We can double this for NVMe, `$0.072/GiB/mo` & `$1,164.14/16TiB/mo`.
